name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
  
      - name: Restore
        run: dotnet restore
  
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Install JRE
        run: sudo apt-get update && sudo apt-get -y install default-jre

      - name: Install Sonar Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run SonarQube analysis
        run: chmod +x ./build/SonarQube.Analysis.sh && ./build/SonarQube.Analysis.sh ${{ secrets.SONARQUBE_TOKEN }}